apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/future-cabinet-439009-i0/notifications/production
        name: notifications
        env:
          - name: PORT
            value: '3000'
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: 379784506666-fh6n61imt1ijs27lfpbjj77iep8foohb.apps.googleusercontent.com
          - name: SMTP_USER
            value: landwaterbnb@gmail.com
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: refreshToken
        ports:
          - containerPort: 3000
